name: Build dump_syms

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up build environment for Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential zlib1g-dev

      - name: Clone linux-syscall-support repository
        run: |
          git clone https://chromium.googlesource.com/linux-syscall-support src/third_party/lss

      - name: Build dump_syms for Linux
        run: |
          ./configure
          make

      - name: Upload Linux binary
        uses: actions/upload-artifact@v2
        with:
          name: dump_syms-linux
          path: |
            src/tools/linux/dump_syms/dump_syms
            src/tools/mac/dump_syms/dump_syms_mac

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: Set up MSBuild and NMake
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: 'latest' # Installe la dernière version de Visual Studio
          include-msbuild: true
          include-nmake: true
          
      - name: Build dump_syms for Windows
        run: |
          cd src/tools/windows
          nmake -f dump_syms.vcproj

      - name: Upload Windows binary
        uses: actions/upload-artifact@v2
        with:
          name: dump_syms-windows
          path: src/tools/windows/Release/dump_syms.exe
