name: Build dump_syms

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up build environment for Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential zlib1g-dev

      - name: Clone Breakpad repository
        run: git clone https://github.com/Nemirtingas/breakpad.git

      - name: Clone linux-syscall-support repository
        run: |
          cd breakpad/src/third_party
          git clone https://chromium.googlesource.com/linux-syscall-support lss

      - name: Build dump_syms for Linux
        run: |
          cd breakpad
          make

      - name: Upload Linux binary
        uses: actions/upload-artifact@v2
        with:
          name: dump_syms-linux
          path: breakpad/src/tools/linux/dump_syms

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up build environment for Windows
        run: |
          choco install -y visualstudio2019buildtools --package-parameters "--includeRecommended --includeOptional"
          choco install -y nasm

      - name: Clone Breakpad repository
        run: git clone https://github.com/Nemirtingas/breakpad.git

      - name: Build dump_syms for Windows
        run: |
          cd breakpad
          .\configure.cmd
          nmake

      - name: Upload Windows binary
        uses: actions/upload-artifact@v2
        with:
          name: dump_syms-windows
          path: breakpad/src/tools/windows/dump_syms.exe
