name: Build dump_syms

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up build environment for Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Clone Breakpad repository
        run: git clone https://github.com/Nemirtingas/breakpad.git

      - name: Build dump_syms for Linux
        run: |
          cd breakpad
          ./configure
          make dump_syms

      - name: Upload Linux binary
        uses: actions/upload-artifact@v2
        with:
          name: dump_syms-linux
          path: breakpad/src/tools/linux/dump_syms

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone Breakpad repository
        run: git clone https://github.com/Nemirtingas/breakpad.git

      - name: Build dump_syms for macOS
        run: |
          cd breakpad
          ./configure
          make dump_syms

      - name: Upload macOS binary
        uses: actions/upload-artifact@v2
        with:
          name: dump_syms-macos
          path: breakpad/src/tools/mac/dump_syms

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone Breakpad repository
        run: git clone https://github.com/Nemirtingas/breakpad.git

      - name: Build dump_syms for Windows
        run: |
          cd breakpad
          ./configure
          make dump_syms

      - name: Upload Windows binary
        uses: actions/upload-artifact@v2
        with:
          name: dump_syms-windows
          path: breakpad/src/tools/win/dump_syms.exe
